qase-pytest/setup.cfg
qase-robotframework/setup.cfg
qase-xctest/setup.cfg

I want to replace qaseio api client with generated version, which is not compatible with current versions of reporters, so I have limited api client version in requirements

limit API client version for current reporters

---

qase-pytest/README.md
qase-pytest/requirements.txt
qase-pytest/src/qaseio/pytest/conftest.py
qase-pytest/src/qaseio/pytest/plugin.py
qase-pytest/src/qaseio/pytest/testops.py

- Fixed issue when qase-pytest-reporter couldn't be run when xdist is installed, but wasn't enabled.
- Fixed an issue with environment id variable

pytest-xdist issue fix

---

qase-pytest/src/qaseio/pytest/conftest.py

`TestOpsPlanLoader.load` expects `id` to be `int`, but it is called from conftest with `config.getoption("qase_testops_plan_id")` which provides string if the parameter is set in CLI. There should be an explicit type conversion between these two, otherwise there's an ApiTypeError

fix ApiTypeError

---

qase-pytest/src/qaseio/pytest/plugin.py
qase-python-commons/src/qaseio/commons/models/result.py
qase-python-commons/src/qaseio/commons/testops.py

`qase.suite` is present but it is not used anywhere. In this PR `Suite` object is created (passing suite title and optional description from decorator) and assigned to `Result` object, so later it can be used when sending results to Qase. [create-result](https://developers.qase.io/reference/create-result) does not allow to specify description, so only title is actually sent.
Fixes #131

[qase-pytest] Send @qase.suite value with test result.

---

qase-pytest/src/qaseio/pytest/plugin.py

Suite data was saved inside of `runtime` object  instead of `runtime.result` so it was ignored and lost.

[qase-pytest] Fix typo that prevented @qase.suite from actually working.

---

qase-pytest/src/qaseio/pytest/conftest.py
qase-pytest/src/qaseio/pytest/plugin.py

capture_logs variable changes from boolean to literal with possible variants: "always", "failed", "off"
changes behaviour on pytest_runtest_makereport hook for new logic
adding default option "off" to options parser in conftest.

Add option to capture logs only on failed tests

---

CONTRIBUTING.md
qase-python-commons/pyproject.toml

Contains one bugfix.
Resolves https://github.com/qase-tms/qase-python/issues/156

Release qase-python-commons 2.0.5 

---

qase-python-commons/pyproject.toml
qase-python-commons/src/qaseio/commons/testops.py

Fixed this issue:
`INTERNALERROR>   File "/Users/gda/PycharmProjects/PytestExamples/.venv/lib/python3.9/site-packages/qaseio/commons/testops.py", line 60, in __init__
INTERNALERROR>     self.environment = self._get_environment(environment, self.project_code)
INTERNALERROR>   File "/Users/gda/PycharmProjects/PytestExamples/.venv/lib/python3.9/site-packages/qaseio/commons/testops.py", line 93, in _get_environment
INTERNALERROR>     for env in response["result"]["entities"]:
INTERNALERROR> TypeError: 'EnvironmentListResponse' object is not subscriptable
`

Fixed receiving environment from Qase

---

CONTRIBUTING.md

Using `git push origin tagname` is the safest option. Unlike it, `git push --tags` can result in pushing all present tags, including some temporary or stale tags.

docs: update contributing instruction on git tags

---

qase-python-commons/pyproject.toml
qase-python-commons/src/qaseio/commons/testops.py

Resolves the following error
TypeError: 'Environment' object is not subscriptable
This error was caused by an update in qaseio client, changing the interface of the Environment object. Now qase-python-commons supports the new interface.

Fix 'object is not subscriptable' in commons

---

.github/workflows/pythonpackage.yml

ci: update GitHub actions to use Node.js v20
--
Update actions/checkout and dorny/paths-filter to the latest versions, using Node.js v20.
This change removes the multiple warnings from the GitHub run view:
`Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, dorny/paths-filter@v2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.`
Update actions/setup-python to the latest version

Update CI workflows

---

qase-pytest/README.md

* Projects don't have test plans upon creation, so using plan=1 results in an error or empty plan.
* Reporter should create a new test run by default, not reuse the same run=1.
* Creating defects from failed autotests is also undesired by default.

pytest: use sane defaults in the config example

---

qase-python-commons/pyproject.toml
qase-python-commons/src/qaseio/commons/testops.py

qase-python-commons: fixed problem with rewrite fields
--
If a test has qase ID then we skip fields like title, description, etc. 
If a test doesn't have qase ID then we assign fields like title, description, etc.

qase-python-commons: fixed problem with rewrite fields

---

qase-pytest/README.md
qase-pytest/docs/CONFIGURATION.md
qase-pytest/docs/UPGRADE.md
qase-python-commons/src/qase/commons/reporters/testops.py

* Update code examples, remove the wrong info about attachments not uploaded.
* Put the example with creating a test run in Qase first, because it's the
first option to try and the most popular one.
* Update the Configuration table: rewrite descriptions, update and explain default values.
* Start the v5 to v6 migration guide.
* Update grammar, style, and formatting in multiple places.

qase-pytest: update docs

---

qase-python-commons/pyproject.toml
qase-python-commons/requirements.txt
qase-python-commons/src/qase/commons/client/api_v1_client.py
qase-python-commons/src/qase/commons/client/base_api_client.py
qase-python-commons/src/qase/commons/loader.py

qase-python-commons: migrate to a new client
--
Migrate from `qaseio` client to `qase-api-client`.
---
release: qase-python-commons 3.0.2b2

release: qase-python-commons 3.0.2b2

---

qase-python-commons/pyproject.toml
qase-python-commons/requirements.txt
qase-python-commons/src/qase/commons/client/api_v1_client.py
qase-python-commons/src/qase/commons/client/api_v2_client.py
qase-python-commons/src/qase/commons/client/base_api_client.py
qase-python-commons/src/qase/commons/config.py
qase-python-commons/src/qase/commons/reporters/testops.py

Added support for API V2. Specify the `useV2` option in the config file or the environment variable `QASE_TESTOPS_USEV2`

release: qase-python-commons 3.0.2b3

---

qase-pytest/pyproject.toml
qase-pytest/src/qase/pytest/plugin.py
qase-python-commons/pyproject.toml
qase-python-commons/src/qase/commons/profilers/sleep.py

qase-pytest: fix sleep profiler
--
The sleep profiler was turned off until the test data collection was completed. Now the profilers will turn off after the test is completed.
---
release: qase-python-commons 3.0.2b4, qase-pytest 6.0.0b2

qase-pytest: fix sleep profiler

---

qase-python-commons/pyproject.toml
qase-python-commons/src/qase/commons/profilers/network.py
qase-python-commons/src/qase/commons/reporters/core.py

Fixed the following issues with network profiler:
- ignore requests to `qase.io` host
- check that `body` and `headers` attributes are in the request
- fix ignoring response for `urllib3` package
- add a creation step for redirected requests

release: qase-python-commons 3.0.2b5

---

qase-python-commons/src/qase/commons/utils.py

Fixed the issue:
`[ ERROR ] Taking listener 'qaseio.robotframework.Listener' into use failed: Importing listener 'qaseio.robotframework.Listener' failed: ModuleNotFoundError: No module named 'pkg_resources'`

release: qase-python-commons 3.0.2b6

---

qase-python-commons/pyproject.toml
qase-python-commons/src/qase/commons/logger.py
qase-robotframework/pyproject.toml
qase-robotframework/src/qaseio/robotframework/listener.py

release: qase-python-commons 3.0.2b7
--
Fixed the issue:
Creating instance failed: OSError: [ Errno 22 ] Invalid argument: './logs\\file.log'
---
release: qase-robotframework 3.0.0b2
--
Fixed an issue with unsupported step status. If the step is `skipped` then mark the step as `blocked`.

release: qase-python-commons 3.0.2b7 and qase-robotframework 3.0.0b2

---

qase-python-commons/pyproject.toml
qase-python-commons/src/qase/commons/config.py
qase-python-commons/src/qase/commons/models/__init__.py
qase-python-commons/src/qase/commons/reporters/testops.py
qase-robotframework/pyproject.toml
qase-robotframework/src/qaseio/robotframework/listener.py

release: qase-python-commons 3.0.2b8
--
Fixed the issues:
- return a correct value from the config if the value didn't find
- mark `Field` model as exported
- fix the problem when the test run  would be completed before the results were sent
---
release: qase-robotframework 3.0.0b2
--
Fixed the issue:
AttributeError: 'Result' object has no attribute 'case'

release: qase-robotframework 3.0.0b2 and qase-python-commons 3.0.2b8

---

qase-robotframework/pyproject.toml
qase-robotframework/src/qase/robotframework/listener.py

release: qase-robotframework 3.0.0b4
--
The logic for extracting Qase ID has been changed. The reporter will extract the Qase ID after ending test.

release: qase-robotframework 3.0.0b4

---

qase-python-commons/pyproject.toml
qase-python-commons/src/qase/commons/logger.py

release: qase-python-commons 3.0.2b9
--
Fixed the issues on Windows OS:
[Errno 22] Invalid argument: `.\\logs\\_20240101_00:00:00`

release: qase-python-commons 3.0.2b9

---

qase-python-commons/pyproject.toml

release: qase-python-commons 3.0.2
--
Updated client packages

release: qase-python-commons 3.0.2

---

qase-api-client/src/qase/api_client_v1/__init__.py
qase-api-client/src/qase/api_client_v1/models/__init__.py
qase-api-client/src/qase/api_client_v1/models/configuration.py
qase-api-client/src/qase/api_client_v1/models/configuration_group.py
qase-api-client/test/test_configuration.py

Fix #212
Rename `Configuration` model to resolve duplicate name issues.

release: qase-api-client 1.0.1

---

qase-pytest/pyproject.toml
qase-pytest/src/qase/pytest/options.py
qase-python-commons/pyproject.toml
qase-python-commons/src/qase/commons/config.py

release: qase-python-commons 3.0.3
--
Fix an issue with getting bool parameter from the config then the parameter's value is False
---
release: qase-pytest 6.0.1
--
Change a name of the complete test run parameter for CLI arguments
Fix #160

release: qase-pytest 6.0.1 and qase-python-commons 3.0.3

---

qase-pytest/docs/UPGRADE.md

Re-phrased this paragraph to clarify that the config should be placed in the **root** of the repository.

Fixed minor grammar error in UPGRADE.md

---

qase-python-commons/pyproject.toml
qase-python-commons/src/qase/commons/reporters/core.py
qase-python-commons/src/qase/commons/reporters/report.py
qase-python-commons/src/qase/commons/reporters/testops.py
qase-python-commons/tests/tests_qase_commons/test_report.py
qase-robotframework/pyproject.toml
qase-robotframework/src/qase/robotframework/listener.py

release: qase-robotframework 3.1.0b2
--
Fix an error:
`AttributeError: 'QaseConfig' object has no attribute 'validate_config'`
---
fix: problem with saving local report
--
Fix an error:
`'Run' object has no attribute 'to_json'`
---
refactor: change type of parameters
--
Change type of parameters for the constructor of reporters.

release: qase-robotframework 3.1.0b2 and qase-python-commons 3.1.0b2

---

qase-python-commons/pyproject.toml
qase-python-commons/src/qase/commons/config.py
qase-python-commons/src/qase/commons/models/config/framework.py
qase-python-commons/src/qase/commons/models/config/qaseconfig.py
qase-python-commons/src/qase/commons/models/config/run.py
qase-python-commons/src/qase/commons/models/config/testops.py
qase-python-commons/src/qase/commons/utils.py

fix: configuration parser should allow uppercase
--
Fix the problem with bool parameters. The config manager didn't get values in uppercase.
[#176]

fix: configuration parser should allow uppercase

---

qase-pytest/src/qase/pytest/plugin.py
qase-robotframework/src/qase/robotframework/listener.py
qase-robotframework/src/qase/robotframework/models.py

feature: add a signature to the test results
--
Implement a method which constructs the signature to each test result.
It takes the file path, the suites, the qase ids and the parameters.

feature: add a signature to the test results

---

qase-pytest/changelog.md
qase-pytest/pyproject.toml
qase-pytest/src/qase/pytest/conftest.py
qase-pytest/src/qase/pytest/options.py
qase-pytest/src/qase/pytest/plugin.py

fix: an issue with `qase-pytest-capture-logs` parameter
--
When using the "qase-pytest-capture-logs" parameter, an error occurred:
`pytest: error: unrecognized arguments: --qase-pytest-capture-logs=true`
Fix #234
---
fix: an issue with `qase-testops-batch-size` parameter
--
When using the "qase-testops-batch-size" parameter, an error occurred:
`TypeError: '>' not supported between instances of 'str' and 'int'`
Fix #235

fix: issues with parameters in qase-pytest

---

qase-pytest/changelog.md
qase-pytest/pyproject.toml
qase-pytest/src/qase/pytest/conftest.py
qase-pytest/src/qase/pytest/options.py

Fixed an issue then `qase-pytest-capture-logs` parameter did not set correct value.
Fix #234

fix: an issue with `qase-pytest-capture-logs` parameter

---

qase-python-commons/pyproject.toml
qase-python-commons/src/qase/commons/reporters/core.py

Add the `get_execution_plan` method that returns a list of test case IDs to execute

feature: add a `get_execution_plan` method

---

qase-pytest/pyproject.toml
qase-pytest/src/qase/pytest/plugin.py

If you use the `testops` mode and specify a plan ID then the reporter will run the tests specified in the test plan based on their IDs.

feature: execution of selected tests

---

qase-python-commons/pyproject.toml
qase-python-commons/src/qase/commons/reporters/report.py

The error occurs when running tests in `report` mode: `'Result' object has no attribute 'to_json'`

fix: an issue with `report` mode

---

qase-python-commons/changelog.md
qase-python-commons/pyproject.toml
qase-python-commons/src/qase/commons/client/api_v1_client.py

Reporters didn't send information about fields, like `title`, `description`, etc, to the Qase. 
Now, the reporters will send all the information about the test case to the Qase.

fix: send all fields

---

qase-pytest/changelog.md
qase-pytest/pyproject.toml
qase-pytest/src/qase/pytest/plugin.py

- Exclude the default parameters that are added by additional libraries and start with `__pytest`
- If you use the `testops` mode and specify a plan ID then the reporter will run the tests specified in the test plan based on their IDs.

fix: execution of selected tests and default parameters

---

qase-python-commons/changelog.md
qase-python-commons/pyproject.toml
qase-python-commons/src/qase/commons/loader.py

Fixed the following issue:
`
HTTPSConnectionPool(host='api.qase.io', port=443): Max retries exceeded with url: /v1/plan/DEMO/1 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1000)'))) `

fix: issue with client

---

qase-api-client/docs/ResultCreate.md
qase-api-client/pyproject.toml
qase-api-client/src/qase/api_client_v1/models/result_create.py

Add a new `param_groups` field to the `ResultCreate` model

feature: add group parameters

---

qase-python-commons/changelog.md
qase-python-commons/pyproject.toml
qase-python-commons/src/qase/commons/client/api_v1_client.py
qase-python-commons/src/qase/commons/models/result.py

Minor release that includes all changes from beta versions 3.1.0b*. 
Also added support for group parameters.

release: qase-python-commons 3.1.0

---

qase-pytest/changelog.md
qase-pytest/pyproject.toml
qase-pytest/src/qase/pytest/plugin.py

Minor release that includes all changes from beta versions 6.1.0b. And also added support for group parameters.

release: qase-pytest 6.1.0

---

qase-robotframework/changelog.md
qase-robotframework/pyproject.toml
qase-robotframework/src/qase/robotframework/listener.py

The reporter will ignore `IF`, `ELSE IF`, `ELSE`, and `END` keywords.
[#247]

feature: Add support `robotframework-tidy`

---

qase-pytest/changelog.md
qase-pytest/pyproject.toml
qase-pytest/src/qase/pytest/plugin.py

This plugin allows you to rerun failed tests.
Each test run will be uploaded as a separate result in Qase.
[#246]

feature: Support `pytest-rerunfailures` plugin

---

qase-pytest/changelog.md
qase-pytest/pyproject.toml
qase-pytest/src/qase/pytest/plugin.py

If the video recording option is enabled and the test fails, the video will be attached to the test result when using Playwright.

feature: upload video for failed tests

---

qase-python-commons/changelog.md
qase-python-commons/pyproject.toml
qase-python-commons/src/qase/commons/client/api_v1_client.py

Support `suite` field in the test case model.
[#248]

release: qase-python-commons 3.1.2

---

qase-pytest/changelog.md
qase-pytest/pyproject.toml
qase-pytest/src/qase/pytest/plugin.py

If we use parameters like this `pytest.mark.parametrize(argnames="foo", argvalues=["bar","baz"])`, then get an error:
```log
INTERNALERROR> File "/usr/local/lib/python3.12/site-packages/qase/pytest/plugin.py", line 79, in pytest_collection_modifyitems
INTERNALERROR> param_name, values = mark.args
INTERNALERROR> ^^^^^^^^^^^^^^^^^^
INTERNALERROR> ValueError: not enough values to unpack (expected 2, got 0)
```
[#264 ]

fix: issue with parameters

---

qase-python-commons/changelog.md
qase-python-commons/pyproject.toml
qase-python-commons/src/qase/commons/logger.py

The logger didn't write logs to the file if the OS used special encoding.
[#247]

fix : issue with logging

---

qase-robotframework/changelog.md
qase-robotframework/pyproject.toml
qase-robotframework/src/qase/robotframework/listener.py

If the test has the `ignore` tag, the reporter will not send the result to Qase.

feature: support `ignore` tag

---

qase-robotframework/changelog.md
qase-robotframework/pyproject.toml
qase-robotframework/src/qase/robotframework/listener.py
qase-robotframework/src/qase/robotframework/models.py
qase-robotframework/src/qase/robotframework/tag_parser.py

You can specify the fields that you want to send to Qase.
```robotframework
Simple test
[Tags]     qase.fields:{ "suite": "my suite", "description": "It is simple test" }
Should Be Equal As Numbers    1    1
```

feature: support `qase.fields` tag

---

qase-robotframework/changelog.md
qase-robotframework/requirements.txt
qase-robotframework/src/qase/robotframework/filter.py
qase-robotframework/src/qase/robotframework/listener.py

If the plan id is specified, the reporter will send the results only for the tests that are in the plan.

feature: support selective execution

---

qase-pytest/changelog.md
qase-pytest/pyproject.toml
qase-pytest/src/qase/pytest/plugin.py

Fixed an issue with the `pytest-xdist` that caused the tests to be run in parallel and completed the test run before the results were uploaded to Qase.

fix: an issue with the `pytest-xdist`

---

qase-pytest/changelog.md
qase-pytest/pyproject.toml
qase-pytest/src/qase/pytest/plugin.py

If a video is attached to the result, it will be added as an attachment. You can configure this functionality using the "video" parameter:
- `--video on` - add a video to each test
- `--video retain-on-failure` - add a video to each filed test
#279

feature: improve video handling in Playwright

---

qase-pytest/changelog.md
qase-pytest/pyproject.toml
qase-pytest/src/qase/pytest/plugin.py

If you specify the `ids` parameter, the reporter will use it as value of parameter in the test case.
```python
@pytest.mark.parametrize("enter", [enter_from_meta, enter_from_expedition, enter_from_news],
ids=["enter_from_meta", "enter_from_expedition", "enter_from_news"])
def test_enter(enter):
enter()
```

feature: improve handling parameters in the `pytest.mark.parametrize`

---

qase-pytest/changelog.md
qase-pytest/pyproject.toml
qase-pytest/src/qase/pytest/plugin.py

feature: improve handling parameters in the pytest.mark.parametrize decorator.
If you specify the `ids` parameter, the reporter will use it as value of parameter in the test case.
```python
@pytest.mark.parametrize("enter", [enter_from_meta, enter_from_expedition, enter_from_news],
                         ids=["enter_from_meta", "enter_from_expedition", "enter_from_news"])
def test_enter(enter):
    enter()
```

release: qase-pytest 6.1.4

---

qase-pytest/changelog.md
qase-pytest/pyproject.toml
qase-pytest/src/qase/pytest/conftest.py
qase-pytest/src/qase/pytest/plugin.py

You don't need to create a `conftest.py` file anymore. The video and trace will be attached to the test result automatically.
You can configure the video and trace recording using the following parameters:
- `--video on` - add a video to each test
- `--video retain-on-failure` - add a video to each filed test
- `--tracing on` - add a trace to each test
- `--tracing retain-on-failure` - add a trace to each filed test
- `--output` - the directory where the video and trace will be saved. By default, the video and trace will be saved in the `test-results` directory.

feature: improve the handling of videos and traces for Playwright tests

---

qase-pytest/changelog.md
qase-pytest/pyproject.toml
qase-pytest/src/qase/pytest/plugin.py

If a test was part of a class, the video and trace were not attached to the test result.
#279

fix: an issue with the handling video and trace recording

---

qase-robotframework/changelog.md
qase-robotframework/pyproject.toml
qase-robotframework/src/qase/robotframework/listener.py

If you use the `pabot` library to run tests in parallel, the reporter will send the results

feature: support `pabot`

---

qase-pytest/changelog.md
qase-pytest/pyproject.toml
qase-pytest/src/qase/pytest/plugin.py

fix: an issue with suites 

---

qase-python-commons/changelog.md
qase-python-commons/pyproject.toml
qase-python-commons/src/qase/commons/models/config/testops.py

If you want to use the API v1 client, specify the `useV2` option in the config file or the environment variable `QASE_TESTOPS_USEV2` as `False`.

feat : use the API v2 client by default

---

qase-python-commons/changelog.md
qase-robotframework/README.md
qase-robotframework/changelog.md
qase-robotframework/pyproject.toml
qase-robotframework/src/qase/robotframework/listener.py
qase-robotframework/src/qase/robotframework/models.py
qase-robotframework/src/qase/robotframework/tag_parser.py

You can specify the params that you want to send to Qase.
```robotframework
*** Variables ***
${var1}            1
${var2}            1
${var3}            2
*** Test Cases ***
Simple test
[Arguments]    ${var1}    ${var2}   ${var3}
[Tags]     qase.params:[var1, var2]
Should Be Equal As Numbers    ${var1}    ${var2}
Should Be Equal As Numbers    ${var3}    ${var3}
```
Only `var1` and `var2` will be sent to Qase.

feat: support `qase.params` tag

---

qase-robotframework/changelog.md
qase-robotframework/pyproject.toml
qase-robotframework/src/qase/robotframework/listener.py

This pull request includes several changes to the `qase-robotframework` project aimed at fixing issues with Pabot and improving test execution handling. The most important changes include updating the version, modifying the `Listener` class to handle a new flag, and updating the changelog.
* [`qase-robotframework/pyproject.toml`](diffhunk://#diff-0af540c11e659381732acbce538f4f9e5a8b2e35fb82931c0d64bce15809761cL7-R7): Updated the project version from `3.2.2` to `3.2.3`.
* [`qase-robotframework/changelog.md`](diffhunk://#diff-3c7f9e6c68fc7a12c5576f8891cdfb49a04fec41f9fda008afa6575d18a18fcbR1-R8): Added an entry for version `3.2.3` detailing the fixed issues with Pabot and test execution.
* `qase-robotframework/src/qase/robotframework/listener.py`: 
- Added a new method `get_last_level_flag` …

fix: resolve pabot issue with duplicated test runs and incomplete executions

---

qase-behave/pyproject.toml
qase-pytest/pyproject.toml
qase-python-commons/pyproject.toml
qase-robotframework/pyproject.toml
qase-tavern/pyproject.toml

#315 
This pull request updates the repository URLs in several `pyproject.toml` files to reflect the change from the "master" branch to the "main" branch. These changes ensure that the documentation and repository links are accurate and up-to-date.
Repository URL updates:
* [`qase-behave/pyproject.toml`](diffhunk://#diff-931cf7a616c4d6ee3bab9cbbf56462aa986af4d12491ffcb43b5ec50f50ee296L39-R39): Updated the repository URL to use the "main" branch.
* [`qase-pytest/pyproject.toml`](diffhunk://#diff-eed5955cc5fa2d784b80f72dfcdfc0377506f787ab2c7991c290250c19bb90bfL40-R40): Updated the repository URL to use the "main" branch.
* [`qase-python-commons/pyproject.toml`](diffhunk://#diff-58b0d6680262cbdcbf5891ee16e7c7551e879b6f6d713b15faf7535ef685f655L28-R28): Updated the repository URL to use the …

fix: update repository links in pyproject.toml

---

qase-python-commons/changelog.md
qase-python-commons/pyproject.toml
qase-python-commons/src/qase/commons/config.py
qase-python-commons/src/qase/commons/models/config/framework.py

- Introduced configuration for custom statuses of xfail-marked tests.
- Default statuses: `skipped` for failed tests and `passed` for successful tests.
- Added methods to read values from `qase.config.json` and environment variables:
- `QASE_PYTEST_XFAIL_STATUS_XFAIL` for failed xfail tests.
- `QASE_PYTEST_XFAIL_STATUS_XPASS` for successful xfail tests.

feat: add support for custom xfail statuses in pytest

---

.github/workflows/pythonpackage.yml
qase-pytest/changelog.md
qase-pytest/pyproject.toml
qase-pytest/src/qase/pytest/plugin.py

Resolved the following issues:
1.	Custom statuses did not work when using `pytest.xfail` within the test body. #321
2.	The test status was displayed incorrectly when using the `skipif` mark. #320
This pull request includes several changes to the `qase-pytest` plugin, focusing on version updates, bug fixes, and improvements to the handling of test statuses and logging.
* [`qase-pytest/pyproject.toml`](diffhunk://#diff-eed5955cc5fa2d784b80f72dfcdfc0377506f787ab2c7991c290250c19bb90bfL7-R7): Updated the version from 6.1.10 to 6.1.11.
* [`qase-pytest/changelog.md`](diffhunk://#diff-609a0b77c1f71e92cd56a2ab7ff5985176f398032295fc4f0bbd9daa415ef9c8R1-R8): Documented fixes for issues with `pytest.xfail` and the `skipif` mark, where custom statuses did not work within the test body and the status …

fix: fix handling of `pytest.xfail` and `skipif` mark

---

qase-api-client/pyproject.toml
qase-api-client/requirements.txt

Hi!
Thank you for your work!
I need to update `urllib3` in my current project, but I can't do that because `qase-api-client` has a frozen version of it `>= 1.25.3, < 2.1.0`.
**Reason of update**: [proxy-authorization in urllib3 request header is not stripped during cross-origin redirects]( https://avd.aquasec.com/nvd/cve-2024-37891)
I updated version in `qase-api-client/pyproject.toml` and in `qase-api-client/requirements.txt` and ran the tests - everything passed
P.S. I haven't found any rules for contributing to the project, so let me know if I've done smth wrong

qase-api-client: Update urllib3 to 2.3.0

---

qase-api-client/pyproject.toml
qase-api-v2-client/pyproject.toml
qase-api-v2-client/requirements.txt

This pull request includes several updates to version numbers and dependency constraints for the `qase-api-client` and `qase-api-v2-client` projects. The changes are primarily focused on updating the versions and dependencies to ensure compatibility and stability.
Version updates:
* [`qase-api-client/pyproject.toml`](diffhunk://#diff-b43468612552c57d4eddc2590928a1a185bca47b58e86f9559215984b02ffc1aL7-R7): Updated the version from `1.1.1` to `1.1.2`.
* [`qase-api-v2-client/pyproject.toml`](diffhunk://#diff-4b54856fa80d46bde8bb753440e85ed7a5cdd8101623294194ee85430c4d3f29L7-R7): Updated the version from `1.1.0` to `1.1.1`.
Dependency updates:
* [`qase-api-v2-client/pyproject.toml`](diffhunk://#diff-4b54856fa80d46bde8bb753440e85ed7a5cdd8101623294194ee85430c4d3f29L25-R25): Updated the `urllib3` …

chore: update urllib3 package version

---

qase-pytest/changelog.md
qase-pytest/pyproject.toml
qase-pytest/src/qase/pytest/decorators.py
qase-pytest/src/qase/pytest/plugin.py

This pull request includes several changes to the `qase-pytest` plugin, primarily focusing on removing unsupported functionality and fixing issues with data handling in decorators. The most important changes include the removal of the `tags` decorator, updates to the version number, and improvements to how data is passed for the `author` and `muted` decorators.
* Removed the unsupported `tags` decorator from the `qase-pytest` plugin as the API does not support working with tags. (`qase-pytest/src/qase/pytest/decorators.py`)
* Removed the `_set_tags` method from the plugin as it is no longer needed due to the removal of the `tags` decorator. (`qase-pytest/src/qase/pytest/plugin.py`)
* Fixed an issue where data was not passed correctly when using the `author` and `muted` decorators. Now, …

fix: `author` and `muted` decorators

---

qase-pytest/changelog.md
qase-pytest/pyproject.toml
qase-pytest/src/qase/pytest/plugin.py

This pull request includes updates to the `qase-pytest` plugin, addressing a bug fix, version bump, and changelog update. The most important changes are:
Bug Fix:
* [`qase-pytest/src/qase/pytest/plugin.py`](diffhunk://#diff-ffa84803e3f2ac6e41e1d504fe2c44d5daec81ae30fd9dd901921a50f7984969L195-R195): Resolved an issue where an AttributeError could occur due to the 'video' attribute not being present on the 'page' object by adding a check using `hasattr`.
Version Update:
* [`qase-pytest/pyproject.toml`](diffhunk://#diff-eed5955cc5fa2d784b80f72dfcdfc0377506f787ab2c7991c290250c19bb90bfL7-R7): Updated the version from 6.1.12 to 6.1.13.
Changelog Update:
* [`qase-pytest/changelog.md`](diffhunk://#diff-609a0b77c1f71e92cd56a2ab7ff5985176f398032295fc4f0bbd9daa415ef9c8R1-R7): Added a new entry for …

fix: handle missing 'video' attribute in pytest plugin

---

qase-pytest/changelog.md
qase-pytest/pyproject.toml
qase-pytest/src/qase/pytest/plugin.py

This pull request includes updates to the `qase-pytest` plugin, focusing on resolving an issue and updating the version. The most important changes are as follows:
Bug Fix:
* Resolved a KeyError ('browser_name') that could occur during `pytest_runtest_makereport` in the pytest plugin.
Version Update:
* Updated the version from `6.1.13` to `6.1.14` in the `pyproject.toml` file.
Code Adjustment:
* Modified the `__build_folder_name` method to check for 'browser_name' in `item.funcargs` before appending it to `path_parts`.
#328

fix: handle missing 'browser_name' attribute in pytest plugin

---

qase-python-commons/changelog.md
qase-python-commons/pyproject.toml
qase-python-commons/src/qase/commons/logger.py

This pull request includes changes to improve the logging functionality in the `qase-python-commons` library, specifically enhancing the concurrency handling and readability of logs. The version number has also been updated to reflect these changes.
Improvements to logging functionality:
* [`qase-python-commons/src/qase/commons/logger.py`](diffhunk://#diff-abba44e6d3cfa2e9999535874f1866b50eecfe8e15ebd23e2f5cb000c4273a90L1-R38): Updated the logger to write logs to a single file from multiple threads by introducing a class-level log file and a threading lock to ensure thread safety.
Version update:
* [`qase-python-commons/pyproject.toml`](diffhunk://#diff-58b0d6680262cbdcbf5891ee16e7c7551e879b6f6d713b15faf7535ef685f655L7-R7): Updated the version number from `3.2.4` to `3.2.5`.
Documentation …

feat: update logger to write logs to a single file from multiple threads

---

qase-pytest/changelog.md
qase-pytest/pyproject.toml
qase-pytest/src/qase/pytest/plugin.py

This pull request includes changes to the `qase-pytest` plugin, focusing on version updates, bug fixes, and enhancements to the attachment handling functionality.
* Updated the version in `pyproject.toml` from 6.1.14 to 6.1.15.
* Resolved an issue where a failure message for attachment uploads was displayed even when attachments were disabled in the configuration.
* Added handling for video attachments in the `handle_xfail_status` method, ensuring videos are attached if the video setting is not turned off.
* Updated imports in `plugin.py` to include `Video` from `qase.commons.models.config.framework`.

fix: suppress attachment upload failure message when disabled in config

---

qase-python-commons/changelog.md
qase-python-commons/pyproject.toml
qase-python-commons/src/qase/commons/client/api_v2_client.py

This pull request includes several updates to the `qase-python-commons` library, focusing on fixing a defect field issue and updating the version number. The most important changes are listed below:
* Resolved an issue where the defect field in the configuration was ignored during test result submission in `qase-python-commons/src/qase/commons/client/api_v2_client.py`.
* Updated the version number from 3.2.6 to 3.2.7 in `qase-python-commons/pyproject.toml`.
* Added a new entry for version 3.2.7 in `qase-python-commons/changelog.md` to document the resolved defect field issue.

fix: ensure `defect` field is properly applied in result submission

---

qase-python-commons/changelog.md
qase-python-commons/pyproject.toml
qase-python-commons/src/qase/commons/client/api_v1_client.py
qase-python-commons/src/qase/commons/client/api_v2_client.py
qase-python-commons/src/qase/commons/models/__init__.py
qase-python-commons/src/qase/commons/models/result.py
qase-python-commons/src/qase/commons/reporters/core.py
qase-python-commons/src/qase/commons/reporters/report.py
qase-python-commons/src/qase/commons/reporters/testops.py

This pull request introduces several important changes to the `qase-python-commons` library, including support for assigning multiple IDs to a single test result, various updates to the logger, and the introduction of a new `InternalResult` model. The changes also involve updating several methods and classes to use the new `InternalResult` model.
* Enabled support for assigning multiple IDs to a single test result, enhancing traceability across test cases.
* Introduced a new `InternalResult` model and updated various methods and classes to use this new model instead of the `Result` model. [[1]](diffhunk://#diff-6e6fb740183246d5bb64af672c81a52dcb14e3ee297b002f8314c905c59d6d20L10-R10) [[2]](diffhunk://#diff-7eed9fb9f5e094348bd96d459bf5a020a640a196e9b931b0a1f9f2aa163729d3L20-R20) …

feat: add support for multiple IDs in a single test result

---

qase-robotframework/changelog.md
qase-robotframework/pyproject.toml
qase-robotframework/src/qase/robotframework/listener.py
qase-robotframework/src/qase/robotframework/models.py
qase-robotframework/src/qase/robotframework/tag_parser.py

This pull request includes several changes to the `qase-robotframework` project to support multiple test case IDs for a single automated test and update dependencies.
* Added support for specifying multiple test case IDs for a single automated test in the `qase-robotframework` plugin. This improves test case association and traceability. (`qase-robotframework/changelog.md` [qase-robotframework/changelog.mdR1-R15](diffhunk://#diff-3c7f9e6c68fc7a12c5576f8891cdfb49a04fec41f9fda008afa6575d18a18fcbR1-R15))
* Updated the version of `qase-robotframework` to `3.3.0` in `pyproject.toml`. (`qase-robotframework/pyproject.toml` [qase-robotframework/pyproject.tomlL7-R7](diffhunk://#diff-0af540c11e659381732acbce538f4f9e5a8b2e35fb82931c0d64bce15809761cL7-R7))
* Updated the dependency …

feat: add support for multiple IDs linking a single test to multiple test cases

---

qase-pytest/changelog.md
qase-pytest/pyproject.toml
qase-pytest/src/qase/pytest/plugin.py

This pull request includes several changes to the `qase-pytest` plugin to improve functionality and code readability. The most important changes involve adding new features, refactoring existing code, and updating documentation.
* Updated `changelog.md` to include a new feature that adds the reason specified in xfail or skip marks to the result comment.
* Refactored `pytest_runtest_makereport` method in `plugin.py` to improve readability and maintainability by breaking down the function into smaller helper methods such as `_process_test_result`, `_handle_failed_test`, `_handle_skipped_test`, `_handle_passed_test`, `_get_xfail_status`, `_set_result_status`, `_attach_logs`, and `_process_playwright_artifacts`.
* Simplified `pytest_sessionfinish` method by using a more concise syntax for …

refactor: restructure pytest_runtest_makereport for improved maintainability

---

qase-robotframework/changelog.md
qase-robotframework/pyproject.toml
qase-robotframework/src/qase/robotframework/listener.py

This pull request includes updates to the `qase-robotframework` project, addressing a bug fix and version increment. The most important changes are detailed below:
Bug Fix:
* [`qase-robotframework/src/qase/robotframework/listener.py`](diffhunk://#diff-bd564381e4cb784a3767fa297740b6a951d3419d0858bc9515b7db2aacef31a8R201): Added the `end_time` attribute to the step execution to ensure the correct setting of execution times.
Version Increment:
* [`qase-robotframework/pyproject.toml`](diffhunk://#diff-0af540c11e659381732acbce538f4f9e5a8b2e35fb82931c0d64bce15809761cL7-R7): Updated the project version from `3.3.0` to `3.3.1`.
Documentation Update:
* [`qase-robotframework/changelog.md`](diffhunk://#diff-3c7f9e6c68fc7a12c5576f8891cdfb49a04fec41f9fda008afa6575d18a18fcbR1-R6): Added a new section …

fix: resolve execution.start time validation issue

---

qase-api-client/docs/CasesApi.md
qase-api-client/docs/QqlTestCase.md
qase-api-client/docs/Run.md
qase-api-client/docs/RunQuery.md
qase-api-client/docs/SearchResponseAllOfResultEntities.md
qase-api-client/docs/TestCaseQuery.md
qase-api-client/pyproject.toml
qase-api-client/src/qase/api_client_v1/api/cases_api.py
qase-api-client/src/qase/api_client_v1/models/qql_test_case.py
qase-api-client/src/qase/api_client_v1/models/run.py
qase-api-client/src/qase/api_client_v1/models/run_query.py
qase-api-client/src/qase/api_client_v1/models/test_case_query.py
qase-api-v2-client/docs/ResultCreate.md
qase-api-v2-client/pyproject.toml
qase-api-v2-client/src/qase/api_client_v2/models/result_create.py

This pull request includes several updates to the `qase-api-client` documentation and codebase, focusing on adding new fields and enhancing the `get_case` method. The most important changes include modifications to support the `include` parameter in the `get_case` method, and the addition of new fields to various models.
Enhancements to `get_case` method:
* [`qase-api-client/docs/CasesApi.md`](diffhunk://#diff-08ccbdcae934f63d6c911ae3e089c24d9cb9f6f6dfba6d8f508e15b07e42dea0L455-R455): Added `include` parameter to the `get_case` method documentation. [[1]](diffhunk://#diff-08ccbdcae934f63d6c911ae3e089c24d9cb9f6f6dfba6d8f508e15b07e42dea0L455-R455) [[2]](diffhunk://#diff-08ccbdcae934f63d6c911ae3e089c24d9cb9f6f6dfba6d8f508e15b07e42dea0R494-R498) …

chore: regenerate API clients based on the latest specification

---

qase-python-commons/changelog.md
qase-python-commons/pyproject.toml
qase-python-commons/requirements.txt
qase-python-commons/src/qase/commons/client/api_v1_client.py
qase-python-commons/src/qase/commons/client/api_v2_client.py
qase-python-commons/src/qase/commons/config.py
qase-python-commons/src/qase/commons/models/__init__.py
qase-python-commons/src/qase/commons/models/config/testops.py
qase-python-commons/src/qase/commons/models/result.py
qase-python-commons/src/qase/commons/reporters/core.py
qase-python-commons/src/qase/commons/reporters/report.py
qase-python-commons/src/qase/commons/reporters/testops.py

This pull request to `qase-python-commons` includes updates to the API clients, improvements in handling multiple QaseID values, and removal of the `useV2` configuration option. Additionally, it simplifies the codebase by removing the `InternalResult` class and related methods.
* Updated API clients to the latest supported versions in `pyproject.toml` and `requirements.txt`. [[1]](diffhunk://#diff-58b0d6680262cbdcbf5891ee16e7c7551e879b6f6d713b15faf7535ef685f655L33-R34) [[2]](diffhunk://#diff-f78310afcec4b84c932d966874710dee9e5b22cedbfbda0724e9f6ca09b1393eL4-R6)
* Removed the `useV2` configuration option, making API v2 the default for sending results. [[1]](diffhunk://#diff-2ab54d02d55a31cc42df2dd1e128fa2b5b07755fc55fddb9aa3b6235d837f3b7R1-R8) Ff979c4fL17R17, …

feat: update supported API client versions and enforce API v2 usage

---

qase-pytest/changelog.md
qase-pytest/pyproject.toml
qase-pytest/requirements.txt
qase-pytest/src/qase/pytest/plugin.py

This pull request includes updates to the `qase-pytest` package, focusing on upgrading dependencies, improving the handling of multiple QaseID values, and removing deprecated configuration options. The key changes are summarized below:
* Updated `qase-python-commons` dependency to version 3.4.0 in both `pyproject.toml` and `requirements.txt` files. [[1]](diffhunk://#diff-eed5955cc5fa2d784b80f72dfcdfc0377506f787ab2c7991c290250c19bb90bfL32-R32) [[2]](diffhunk://#diff-0c5c14f5d8f34f07929c43c3648a171864ec6456aff2972073a9d9ca45b10847L4-R4)
* Improved logic for handling multiple QaseID values in test results by updating methods to use `testops_ids` instead of `testops_id` in `plugin.py`. [[1]](diffhunk://#diff-ffa84803e3f2ac6e41e1d504fe2c44d5daec81ae30fd9dd901921a50f7984969L275-R275) …

feat: update supported core package version and enforce API v2 usage

---

qase-robotframework/changelog.md
qase-robotframework/pyproject.toml
qase-robotframework/src/qase/robotframework/listener.py

This pull request updates the `qase-robotframework` plugin to version 3.4.1, addressing a bug in handling conditional logic within test steps and ensuring proper parsing. Below are the most important changes:
* Fixed an issue where steps containing IF/ELSE conditional logic were not properly parsed and represented in test cases. This ensures accurate handling of conditional structures. (`qase-robotframework/changelog.md`, `qase-robotframework/src/qase/robotframework/listener.py`) [[1]](diffhunk://#diff-3c7f9e6c68fc7a12c5576f8891cdfb49a04fec41f9fda008afa6575d18a18fcbR1-R7) [[2]](diffhunk://#diff-bd564381e4cb784a3767fa297740b6a951d3419d0858bc9515b7db2aacef31a8R220)
* Updated the version of the plugin from `3.4.0` to `3.4.1` in `pyproject.toml` to reflect the new release. …

fix: correctly handle steps with IF/ELSE sections

---

qase-python-commons/changelog.md
qase-python-commons/pyproject.toml
qase-python-commons/src/qase/commons/client/api_v2_client.py
qase-python-commons/src/qase/commons/logger.py
qase-python-commons/src/qase/commons/models/basemodel.py
qase-python-commons/src/qase/commons/models/result.py
qase-python-commons/src/qase/commons/models/run.py
qase-python-commons/src/qase/commons/models/step.py
qase-python-commons/src/qase/commons/reporters/report.py

This pull request introduces several updates to the `qase-python-commons` library, focusing on bug fixes, enhancements to attachment handling, and code cleanup. The most notable changes include fixing enum serialization, refactoring attachment handling to improve encapsulation, and removing unused fields and methods from models.
* Fixed an issue with enum serialization in models by updating the `__str__` method in `BaseModel` to handle enums properly, allowing serialization as either names or values. (`qase-python-commons/src/qase/commons/models/basemodel.py`)
* Replaced the `attachments` list in `Step` with a new `add_attachment` method in `StepExecution` to encapsulate attachment logic. (`qase-python-commons/src/qase/commons/models/step.py`) …

fix: correct enum serialization in models

---

qase-robotframework/changelog.md
qase-robotframework/pyproject.toml
qase-robotframework/src/qase/robotframework/listener.py

This pull request introduces a bug fix and refactors the step parsing logic in the `qase-robotframework` project. The changes aim to resolve issues with conditional execution steps and improve the maintainability of the codebase. Below are the key updates:
* **Changelog Update**: Documented the fix for handling steps with conditional execution logic to ensure proper structure and reporting in version `3.4.2`. (`qase-robotframework/changelog.md`, [qase-robotframework/changelog.mdR1-R6](diffhunk://#diff-3c7f9e6c68fc7a12c5576f8891cdfb49a04fec41f9fda008afa6575d18a18fcbR1-R6))
* **Improved Step Parsing Logic**: Refactored the `__parse_steps` method in `qase/robotframework/listener.py` to:
- Use a cleaner loop structure by iterating directly over `result_step.body`.
- Introduce helper methods …

fix: correct handling of conditional steps execution

---

qase-python-commons/changelog.md
qase-python-commons/pyproject.toml
qase-python-commons/src/qase/commons/client/api_v2_client.py

- Updated version to 3.4.4 in pyproject.toml.
- Fixed an issue with the usage of the `pytest.skip` method inside a step body.
- Enhanced execution status handling for untested steps in the API client.

fix:  pytest.skip usage inside a step body

---

qase-api-client/pyproject.toml
qase-api-v2-client/pyproject.toml

- Updated version to 1.2.2 in pyproject.toml for both qase-api-client and qase-api-v2-client.
- Changed urllib3 dependency version to >= 2.5.0 for compatibility.

chore: update version to 1.2.2 and adjust urllib3 dependency

---

qase-python-commons/changelog.md
qase-python-commons/pyproject.toml
qase-python-commons/src/qase/commons/client/api_v1_client.py
qase-python-commons/src/qase/commons/config.py
qase-python-commons/src/qase/commons/models/config/testops.py
qase-python-commons/tests/tests_qase_commons/test_configurations.py

- Introduced the ability to specify test run configurations via `qase.config.json`, environment variables, or CLI parameters.
- Added new models: `ConfigurationValue` and `ConfigurationsConfig` for managing configurations.
- Implemented methods in `ApiV1Client` for retrieving, finding, and creating configurations through the API.
- Updated version to 3.5.3 in pyproject.toml.
- Enhanced changelog to document new features and improvements.

feat: add support for test run configurations

---

qase-behave/changelog.md
qase-behave/docs/CONFIGURATION.md
qase-behave/pyproject.toml
qase-behave/src/qase/behave/formatter.py
qase-pytest/changelog.md
qase-pytest/docs/CONFIGURATION.md
qase-pytest/pyproject.toml
qase-pytest/src/qase/pytest/conftest.py
qase-pytest/src/qase/pytest/options.py
qase-robotframework/docs/CONFIGURATION.md
qase-tavern/changelog.md
qase-tavern/docs/CONFIGURATION.md
qase-tavern/pyproject.toml
qase-tavern/src/qase/tavern/conftest.py
qase-tavern/src/qase/tavern/options.py

- Updated versions in pyproject.toml for qase-behave, qase-pytest, and qase-tavern.
- Added support for filtering test results by status across all plugins.
- Enhanced documentation to include configuration examples for status filtering.
- Updated changelogs to reflect the addition of this feature.

feat: release versions with status filtering support

---

qase-python-commons/changelog.md
qase-python-commons/pyproject.toml
qase-python-commons/src/qase/commons/client/api_v1_client.py
qase-python-commons/src/qase/commons/config.py
qase-python-commons/src/qase/commons/models/config/run.py
qase-python-commons/src/qase/commons/models/external_link.py

- Updated version to 3.5.6 in pyproject.toml.
- Added functionality to update external links for test runs.
- Introduced new models and methods to handle external link configuration.
- Enhanced changelog to document the new feature.
This release improves integration with external issue tracking systems.

feat: release version 3.5.6 with support for external links in test runs

---

qase-pytest/changelog.md
qase-pytest/pyproject.toml
qase-pytest/src/qase/pytest/plugin.py

- Updated version to 7.0.1 in pyproject.toml.
- Fixed an issue with the `pytest.xfail` mark in the plugin.
- Updated changelog to reflect the new version and changes.
This release addresses a bug related to the `pytest.xfail` mark, improving test handling.
#402

fix: bug with pytest.xfail mark

---

qase-python-commons/README.md
qase-python-commons/changelog.md
qase-python-commons/docs/STATUS_MAPPING.md
qase-python-commons/pyproject.toml
qase-python-commons/src/qase/__init__.py
qase-python-commons/src/qase/commons/config.py
qase-python-commons/src/qase/commons/models/config/qaseconfig.py
qase-python-commons/src/qase/commons/models/result.py
qase-python-commons/src/qase/commons/reporters/core.py
qase-python-commons/src/qase/commons/status_mapping/__init__.py
qase-python-commons/src/qase/commons/status_mapping/status_mapping.py
qase-python-commons/tests/tests_qase_commons/test_status_mapping.py
qase-python-commons/tests/tests_qase_commons/test_status_mapping_config.py

- Updated version to 4.0.1 in pyproject.toml.
- Added support for status mapping, allowing transformation of test result statuses based on configuration.
- Updated changelog to reflect the new version and changes.
- Enhanced README to include additional projects utilizing the package.
- Introduced new documentation for status mapping functionality.
This release improves test result handling and provides better integration with various testing frameworks.

feat: release version 4.0.1 with status mapping support
