- qase-pytest/src/qaseio/pytest/testops.py
Fixed an issue with passing plan_id to Qase API
> Plan_id fix

- qase-pytest/requirements.txt
- qase-pytest/src/qaseio/pytest/options.py
- qase-python-commons/src/qaseio/commons/testops.py
- Fixed an issue with missing command options
- Fixed an issue with empty `environment` variable
> Missing options

- qase-python-commons/src/qaseio/commons/utils.py
Fixed an issue with host data on windows
> Fixed an issue with host data on windows

- qase-python-commons/src/qaseio/commons/models/result.py
```
INTERNALERROR>     return json.dumps(self, default=lambda o: o.__dict__, sort_keys=False, indent=4)
INTERNALERROR> AttributeError: 'PosixPath' object has no attribute '__dict__'
```
Error then ran in "report" mode fixed
> AttributeError fix in  result.py

- qase-python-commons/src/qaseio/commons/testops.py
FIxes #138, both name and id now are supported.
Changes:
* `if environment:` moved below `self.enable = True` as its behaviour now depends on whether testops mode is enabled.
* `self.environemnt_id` is not set anymore as it seems it wasn't used anywhere
* extended condition for cases when environment id is passed as it will have type `int` only if qase.config.json is used, env variable and pytest option always return string.
* name lookup won't be performed if environment value is numerical, so it will not work for numerical only environment names.
> [qase-python-commons] Implement env lookup by name.

- qase-pytest/README.md
Updated configuration and upgrade links
> Updated README.md in qase-pytest

- qase-python-commons/src/qaseio/commons/models/attachment.py
Fixed uploading attachments by file paths
> Fixed uploading attachments by file paths

- qase-pytest/pyproject.toml
- qase-pytest/src/qaseio/pytest/options.py
Wasn't working because of a typo in the options setup.
Fixes #160
> qase-pytest: fix --qase-testops-run-complete

- qase-python-commons/pyproject.toml
- qase-python-commons/src/qaseio/commons/interceptor.py
Fixed this issue https://github.com/qase-tms/qase-python/issues/134
> Fixed response wrapper. Resolves #134

- qase-python-commons/pyproject.toml
- qase-python-commons/src/qaseio/commons/testops.py
qase-python-commons: fix preconditions field
--
Resolves the following problem:
When a precondition field was specified, it was not updated in the TMS. This hotfix resolves this issue.
---
qase-python-commons: apply standard Python file format
--
- applied standard indents
- removed extra brackets
- removed unused imports
> qase-python-commons: fix preconditions field

- qase-pytest/src/qase/pytest/plugin.py
- qase-python-commons/pyproject.toml
- qase-python-commons/src/qase/commons/config.py
- qase-python-commons/src/qase/commons/logger.py
- qase-python-commons/src/qase/commons/models/attachment.py
- qase-python-commons/src/qase/commons/models/basemodel.py
- qase-python-commons/src/qase/commons/models/relation.py
- qase-python-commons/src/qase/commons/models/result.py
- qase-python-commons/src/qase/commons/models/run.py
- qase-python-commons/src/qase/commons/models/step.py
- qase-python-commons/src/qase/commons/models/suite.py
- qase-python-commons/src/qase/commons/reporters/core.py
- qase-python-commons/src/qase/commons/reporters/testops.py
- qase-python-commons/tests/tests_qase_commons/models/test_run.py
qase-python-commons: add more debug logs
--
Added a base class for all models. It helps to serialize the models to json.
Added logs before and after important functions in the common package.
---
qase-python: fixed an issue with xdist
--
Fixed the issue where the test run would not complete if the xDist package was disabled or not installed.
> qase-python-commons: add more debug logs

- qase-pytest/src/qase/pytest/plugin.py
- qase-python-commons/pyproject.toml
- qase-python-commons/src/qase/commons/client/api_v1_client.py
- qase-python-commons/src/qase/commons/client/base_api_client.py
- qase-python-commons/src/qase/commons/models/attachment.py
- qase-python-commons/src/qase/commons/reporters/core.py
- qase-python-commons/src/qase/commons/reporters/report.py
- qase-python-commons/src/qase/commons/reporters/testops.py
- qase-robotframework/src/qaseio/robotframework/listener.py
qase-python-common: refactored an api client
--
The following changes:
- add abstract class for api clients
- add implementation for the api client v1
- fixed problem with attachments
- change `complete_run` method signature
> qase-python-common: refactored an api client

- qase-pytest/README.md
- qase-robotframework/README.md
- qase-robotframework/docs/CONFIGURATION.md
- qase-robotframework/docs/UPGRADE.md
- qase-robotframework/pyproject.toml
> release: qase-robotframework 3.0.0b1

- qase-python-commons/pyproject.toml
- qase-python-commons/src/qase/commons/client/api_v1_client.py
- qase-python-commons/src/qase/commons/logger.py
- qase-python-commons/src/qase/commons/models/step.py
Fixed the issues:
- Creating instance failed: OSError: [ Errno 22 ] Invalid argument: './logs\\file.log'
- Fixed an issue with unsupported step status. If the step is `skipped` then mark the step as `blocked`.
> release: qase-python-commons 3.0.2b7

- qase-pytest/README.md
- qase-pytest/pyproject.toml
> release: qase-pytest 6.0.0

- qase-robotframework/README.md
- qase-robotframework/pyproject.toml
> release: qase-robotframework 3.0.0

- qase-api-client/pyproject.toml
> release: qase-api-client 1.0.1

- qase-python-commons/pyproject.toml
- qase-python-commons/src/qase/commons/reporters/testops.py
feature: show a link if a test is failed
--
Show the link to the test result in the Qase then the test is failed.
> feature: show a link if a test is failed

- README.md
- mark `qaseio` as deprecated
- add `qase-api-client` and `qase-api-v2-client` clients
- remove `qase-pytest-bdd`
> docs: update the root readme

- qase-api-client/docs/Defect.md
- qase-api-client/docs/EnvironmentsApi.md
- qase-api-client/docs/Run.md
- qase-api-client/docs/RunCreate.md
- qase-api-client/docs/SearchResponseAllOfResultEntities.md
- qase-api-client/pyproject.toml
- qase-api-client/src/qase/api_client_v1/api/environments_api.py
- qase-api-client/src/qase/api_client_v1/models/run.py
- qase-api-client/src/qase/api_client_v1/models/run_create.py
Added search for environments and creation of test runs with the addition of an environment slug
> feature: update the api client

- qase-pytest/docs/CONFIGURATION.md
Add information about `debug` mode
> docs: update the configuration page

- qase-pytest/pyproject.toml
- qase-pytest/src/qase/pytest/plugin.py
Fix the issue `TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'`
[#226]
> fix: an issue with suites

- qase-pytest/changelog.md
- qase-python-commons/changelog.md
- qase-robotframework/changelog.md
Add the changelogs for the following packages:
- qase-pytest
- qase-robotframework
- qase-python-commons
> docs: add changelogs

- qase-robotframework/changelog.md
- qase-robotframework/pyproject.toml
- qase-robotframework/src/qase/robotframework/listener.py
- qase-robotframework/src/qase/robotframework/method.py
- qase-robotframework/src/qase/robotframework/plugin.py
Implement the `qase.attach()` method which adds attachments to a step.
> feature: ability to attach attachments to step implementations

- qase-python-commons/pyproject.toml
- qase-python-commons/src/qase/commons/reporters/core.py
Add `get_execution_plan` method that returns a list of IDs to run tests
> feature: add a new method

- qase-robotframework/changelog.md
- qase-robotframework/pyproject.toml
Minor release that includes all changes from beta versions 3.1.0b.
> release: qase-robotframework 3.1.0

- qase-pytest/changelog.md
- qase-pytest/pyproject.toml
- qase-pytest/src/qase/pytest/plugin.py
```log
INTERNALERROR>     video = item.funcargs['page'].video
INTERNALERROR>             ~~~~~~~~~~~~~^^^^^^^^
INTERNALERROR> KeyError: 'page'
```
> fix: issue with the video uploading

- qase-robotframework/changelog.md
- qase-robotframework/pyproject.toml
- qase-robotframework/src/qase/robotframework/listener.py
Fixed the issue:
```log
Calling method 'end_test' of listener 'qase.robotframework.Listener' failed: IndexError: list index out of range
```
[#247]
> fix: issue with a listener

- qase-robotframework/changelog.md
- qase-robotframework/pyproject.toml
- qase-robotframework/src/qase/robotframework/listener.py
Migrate the listener to the `ROBOT_LISTENER_API_VERSION` version 3.
> refactor: listener

- qase-api-client/docs/Author.md
- qase-api-client/pyproject.toml
- qase-api-client/src/qase/api_client_v1/models/author.py
Add new fields:
- `author_id`
- `entity_id`
> feature: update `author` model

- qase-python-commons/changelog.md
- qase-python-commons/pyproject.toml
- qase-python-commons/src/qase/commons/client/api_v1_client.py
You can specify `author name` or `email` in fields.
> feature : support `author` field

- qase-python-commons/changelog.md
- qase-python-commons/pyproject.toml
- qase-python-commons/src/qase/commons/client/api_v1_client.py
```log
"attachments": [attach.hash for attach in attached],
AttributeError: 'list' object has no attribute 'hash'
```
> fix : an issue with the `upload_attachment` method

- qase-python-commons/changelog.md
- qase-python-commons/pyproject.toml
- qase-python-commons/src/qase/commons/client/api_v1_client.py
- qase-python-commons/src/qase/commons/models/config/framework.py
You can specify the `video`, `trace` and `output` options.
> feature : added configuration for Playwright framework

- qase-pytest/README.md
- qase-pytest/docs/CONFIGURATION.md
Updated the configuration section
> docs: update readme

- qase-pytest/docs/CONFIGURATION.md
- qase-robotframework/docs/CONFIGURATION.md
Updated `execution plan` parameter
> docs: update configuration

- qase-pytest/changelog.md
- qase-pytest/pyproject.toml
- qase-pytest/src/qase/pytest/plugin.py
Fixed an issue with parameters:
```log
INTERNALERROR>   File "/venv/lib/python3.9/site-packages/qase/pytest/plugin.py", line 331, in _set_params
INTERNALERROR>     value = str(ids[i])
INTERNALERROR> IndexError: list index out of range
```
> fix: an issue with parameters

- README.md
- Added clear section headers for better readability
- Expanded descriptions for each project, including use cases and recommendations
- Marked deprecated projects explicitly and provided migration guidance
- Refined language for consistency and clarity
> docs: improve documentation for Qase TestOps Python reporters

- README.md
- examples/behave/README.md
- examples/behave/qase.config.json
- examples/behave/requirements.txt
- examples/behave/tests/features/parametrized.feature
- examples/behave/tests/features/simple.feature
- examples/behave/tests/features/steps/steps.py
- examples/behave/tests/features/suites.feature
- qase-behave/LICENSE.txt
- qase-behave/README.md
- qase-behave/changelog.md
- qase-behave/docs/CONFIGURATION.md
- qase-behave/docs/usage.md
- qase-behave/pyproject.toml
- qase-behave/requirements.txt
- qase-behave/src/qase/behave/formatter.py
- qase-behave/src/qase/behave/utils.py
- qase-behave/tests/test_utils.py
- qase-python-commons/changelog.md
- qase-python-commons/pyproject.toml
- qase-python-commons/src/qase/commons/client/api_v2_client.py
refactor: improve action formatting for Gherkin steps
- Refactored Gherkin step handling to concatenate `keyword` and `name` into the `action` field, ensuring both are included when they differ.
- Enhances clarity and completeness of the step action data.
---
feat: implement Behave reporter
---
feat: add Behave example project
> feat: implement Behave reporter

- qase-robotframework/changelog.md
- qase-robotframework/pyproject.toml
- qase-robotframework/src/qase/robotframework/listener.py
- qase-robotframework/src/qase/robotframework/method.py
This pull request includes several updates to the `qase-robotframework` project, focusing on fixing issues with test step handling and attachment processing, as well as updating the project version. The most important changes include the following:
* Fixed handling of test steps with the `Message` type to ensure proper processing (`qase-robotframework/src/qase/robotframework/listener.py`).
* Resolved an issue with attachment handling, enabling correct attachment uploads (`qase-robotframework/src/qase/robotframework/method.py`).
* Updated the project version to 3.2.4 in the `pyproject.toml` file (`qase-robotframework/pyproject.toml`).
* Added a changelog entry for version 3.2.4, detailing the new fixes (`qase-robotframework/changelog.md`).
> fix: fixed issues with steps of type Message and attachment handling

- qase-behave/changelog.md
- qase-behave/pyproject.toml
- qase-behave/src/qase/behave/formatter.py
This pull request includes updates to the `qase-behave` plugin to resolve an issue with ignored tests and increment the version number. The most important changes include updating the version in the `pyproject.toml` file, modifying the `formatter.py` file to handle ignored scenarios correctly, and updating the changelog to reflect these changes.
* [`qase-behave/pyproject.toml`](diffhunk://#diff-931cf7a616c4d6ee3bab9cbbf56462aa986af4d12491ffcb43b5ec50f50ee296L7-R7): Updated the version from `1.0.0` to `1.0.1`.
* [`qase-behave/src/qase/behave/formatter.py`](diffhunk://#diff-ff804f5ce59f7b77af89343ad8149fba466feabb75b9154266a061e1fa8e21e4L35-R35): Modified the `scenario` method to check if `__current_scenario.ignore` is `False` before completing the execution and adding the result.
* …
> fix: resolve issue with qase.ignore tag not preventing result submission

- qase-tavern/changelog.md
- qase-tavern/pyproject.toml
- qase-tavern/src/qase/tavern/plugin.py
- qase-tavern/tests/test_extractor.py
This pull request includes several important changes to the `qase-tavern` project, primarily focusing on adding support for multiple test case IDs and updating dependencies. The most significant changes include updating the changelog, modifying the `extract_qase_id` method, and updating the project version and dependencies.
* [`qase-tavern/changelog.md`](diffhunk://#diff-21444be85266fa14b51a7d34be1f2ee54b319953683556c6ae9de9d732ac56e1R1-R14): Added support for specifying multiple test case IDs for a single automated test to improve test case association and traceability.
* [`qase-tavern/src/qase/tavern/plugin.py`](diffhunk://#diff-5cccb0e287a9097db929222dcf5ca263f4eadf2f5c4f678600ae83cee77c66a5L138-R150): Modified the `extract_qase_id` method to handle multiple test case IDs and return a …
> feat: add support for multiple IDs linking a single test to multiple test cases

- qase-python-commons/changelog.md
- qase-python-commons/pyproject.toml
- qase-python-commons/src/qase/commons/reporters/core.py
- qase-python-commons/src/qase/commons/util/__init__.py
- qase-python-commons/src/qase/commons/util/host_data.py
This pull request introduces significant changes to the `qase-python-commons` library, focusing on enhancing logging capabilities and adding functionalities for better debugging and traceability. The main changes include logging host system details, updating the version, and adding utility functions to gather host information.
Enhancements to logging and debugging:
* [`qase-python-commons/changelog.md`](diffhunk://#diff-2ab54d02d55a31cc42df2dd1e128fa2b5b07755fc55fddb9aa3b6235d837f3b7R1-R7): Added a new entry for version 3.3.2, highlighting the logging of host system details and output of installed packages.
* [`qase-python-commons/src/qase/commons/reporters/core.py`](diffhunk://#diff-6d1d3c1fb9c7f62ce3fefb241b625182e5dc2adc3b319a8861fe944f76c9da81R13-R22): Modified the `QaseCoreReporter` …
> feat: add logging of host information and installed packages

- qase-pytest/changelog.md
- qase-pytest/pyproject.toml
- qase-pytest/src/qase/pytest/decorators.py
- Added support for indirect parameters in `qase.parametrize_ignore` decorator.
- Updated version to 6.3.4 in pyproject.toml.
- Enhanced changelog to reflect new features.
> feat: release version 6.3.4 with new features and enhancements

- qase-python-commons/changelog.md
- qase-python-commons/pyproject.toml
- qase-python-commons/src/qase/commons/reporters/testops.py
- Fixed an issue where the test run was being completed before the results were uploaded.
- Updated version to 3.5.1 in pyproject.toml.
- Enhanced changelog to reflect the bug fix.
#373
> fix: issue where the test run was being completed before the results were uploaded

- qase-behave/changelog.md
- qase-behave/pyproject.toml
- qase-behave/src/qase/behave/utils.py
- Fixed an issue with the start time of the step execution.
- Updated version to 1.1.2 in pyproject.toml.
- Enhanced changelog to reflect the bug fix.
> fix : issue with the start time of the step execution

- qase-python-commons/changelog.md
- qase-python-commons/pyproject.toml
- qase-python-commons/src/qase/commons/reporters/testops.py
- Updated version to 3.5.2 in pyproject.toml.
- Fixed an issue where the test run wasn't being completed before the results were uploaded.
- Enhanced changelog to reflect the changes made.
> fix: issue where the test run wasn't being completed before the results were uploaded

- qase-python-commons/changelog.md
- qase-python-commons/docs/STATUS_FILTER.md
- qase-python-commons/pyproject.toml
- qase-python-commons/src/qase/commons/config.py
- qase-python-commons/src/qase/commons/models/config/testops.py
- qase-python-commons/src/qase/commons/reporters/testops.py
- Updated version to 3.5.4 in pyproject.toml.
- Added support for filtering test results by status, allowing users to exclude specific statuses from reporting.
- Introduced new documentation for status filtering functionality, including configuration examples and use cases.
- Enhanced changelog to reflect the addition of this feature.
> feat: release version 3.5.4 with status filtering support

- qase-python-commons/changelog.md
- qase-python-commons/docs/LOGGING.md
- qase-python-commons/pyproject.toml
- qase-python-commons/src/qase/commons/config.py
- qase-python-commons/src/qase/commons/logger.py
- qase-python-commons/src/qase/commons/models/config/qaseconfig.py
- qase-python-commons/src/qase/commons/reporters/core.py
- qase-python-commons/tests/tests_qase_commons/test_logger.py
- qase-python-commons/tests/tests_qase_commons/test_logging_config.py
- Updated version to 4.1.0 in pyproject.toml.
- Added support for logging configuration, allowing control over console and file output.
- Introduced new documentation for logging configuration.
- Updated changelog to reflect the new version and changes.
This release enhances logging capabilities, providing better control over log message output across various components.
> feat: release version 4.1.0 with logging configuration support
